{
 "title": "Belabox Cloud",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "📈 Битрейт, Сеть, Потери",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "publisher_bitrate{name=\"$name\"}",
     "legendFormat": "bitrate (Mbps)"
    },
    {
     "expr": "publisher_dropped_packets{name=\"$name\"}",
     "legendFormat": "dropped pkts",
     "yAxis": 2
    }
   ]
  },
  {
   "title": "📶 RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "publisher_rtt{name=\"$name\"}",
     "legendFormat": "rtt"
    }
   ]
  },
  {
   "title": "⌛ Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "publisher_latency_ms{name=\"$name\"}",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}